version: "3.9"

services:
  kadmin-arklin2:
    depends_on:
      - mongodb
    build: "./"
    restart: always
    env_file:
      - .env.production
    environment:
      - MONGODB_PORT=27017
      - MONGODB_HOST=mongodb
      - MONGODB_USER=botusername
      - MONGODB_PASSWD=botpasswd
      - MONGODB_DATABASE=botdatabase
    volumes:
      - ./mount/bot/:/mount/
    networks:
      - botnet

  mongodb:
    image: mongo
    volumes:
      - './mount/mongodb:/data/db'
    environment:
      MONGO_INITDB_DATABASE: botdatabase
      MONGO_INITDB_ROOT_USERNAME: botusername
      MONGO_INITDB_ROOT_PASSWORD: botpasswd
    networks:
      - botnet

networks:
  botnet:
